[[main]]
  name = "👤 Profile"
  pageRef = "/profile"
  weight = 10

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/tamada"
  weight = 100

[[footer]]
  name = "📲 Contact"
  weight = 10
  pageRef = "/contact"

[[footer]]
  name = "🏷️ Tags"
  weight = 100
  pageRef = "/tags"

[[footer]]
  name = "🌸 About"
  weight = 50
  pageRef = "/about"

[[footer]]
  name = "🔒 Privacy Policy"
  weight = 60
  pageRef = "/privacy-policy"

[[footer]]
  name = "🍪 Cookie Settings"
  weight = 70
  url = "#consent-settings"
