baseURL = "https://tamada.github.io/"
languageCode = "en-us"
title = "Haruaki TAMADA"
theme = "cayman-hugo-theme"
canonifyurl = true
paginate = 6
disqusShortname = "htamada"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

googleAnalytics = "UA-62401730-5"

[params]
    project_name = "Haruaki TAMADA"
    project_tagline = "Researcher of Software Protectoin, and Developer!"
    project_logo = "images/harry.png"
    dateFormat = "Jan 02, 2006"
    footer = "Made with [Hugo](https://gohugo.io/). Theme by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [GitHub Pages](https://pages.github.com/)."
    amazonJpAffiliate = "tamanikki07-22"

[menu]
    [[menu.nav]]
        name = ":house: Home"
        url = "/"
        weight = 1
    [[menu.nav]]
        name = ":rocket: Projects"
        url = "/projects"
        weight = 2
    [[menu.nav]]
        name = ":bulb: Research"
        url = "/research"
        weight = 3
    [[menu.nav]]
        name = ":bust_in_silhouette: Profile"
        url = "/profile"
        weight = 4
    [[menu.nav]]
        name = ":thinking: Blog"
        url = "/Blog"
        weight = 5
