baseURL = "https://tamada.github.io/"
languageCode = "en-us"
title = "Haruaki TAMADA"
theme = "hugo-theme-dream"
pagenate = 9

googleAnalytics = "UA-62401730-5"
copyright = "Haruaki Tamada"

[params]
    author = "Haruaki Tamada"
    avatar = "/images/harry.jpg"
    motto = "人事が万事塞翁が馬, Que Sera, Sera"
    
    background = "black"
    linkColor = "seagreen"

    twitter = "tama5"
    github = "tamada"
    email = "tamada@cafebabe.jp"

    siteStartYear = 2007

    darkLinkColor = "darkseagreen"
    darkNav = true
    dark404Button = true