baseURL = "https://tamada.github.io/"
languageCode = "en-us"
title = "Haruaki TAMADA"
theme = "hugo-cards"
pagenate = 9

googleAnalytics = "UA-62401730-5"

[params]
    buildBy = "Haruaki Tamada"
    defaultimage = "prost.png"
    avatarIcon = "harry.jpg"

    twitter = "https://twitter.com/tama5"
    github = "https://github.com/tamada"

[params.copyright]
    name = "tamada"
    link = "https://tamada.github.io/"
