baseURL = "https://tamada.github.io/"
languageCode = "en-us"
title = "Haruaki TAMADA"
theme = "hugo-swift-theme"
paginate = 6

googleAnalytics = "UA-62401730-5"

[params]
    author = "Haruaki Tamada"
    logo = "harry.png"
    ga_analytics = "UA-62401730-5"
    twitter = "tama5"

[params.staticman]

