name: commit_and_push
description: >
  An action to commit and push changes to the repository.
inputs:
  commit_message:
    description: 'The commit message to use for the changes.'
    required: true
  branch_name:
    description: 'The target branch to commit and push changes to (e.g., main, trunk).'
    required: true
  working_directory:
    description: 'The working directory where changes are made.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"

    - name: Commit and push changes
      shell: bash
      run: |
        cd ${{ inputs.working_directory }}
        git commit -m "${{ inputs.commit_message }}" || true
        git push origin ${{ inputs.branch_name }}
