name: Conditional Publish by Branch Age

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup hugo
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: 'latest'
              extended: true

        - name: Build and update site
          run:  |
            mkdir -p public
            hugo --minify

        - name: Upload artifacts
          uses: actions/upload-pages-artifact@v3
          with:
            path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5