name: Conditional Publish by Branch Age

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  call-hugo-build:
    uses: tamada/workflows/.github/workflows/build-hugo-and-publish.yaml@main
    with:
      workdir: "."
      branch: trunk
    permissions:
      contents: read
      pages: write
      id-token: write
